name: CI/CD - VacApp Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar pruebas
        run: dotnet test --configuration Release --verbosity normal

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir y subir imagen Docker
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/vacapp-backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/vacapp-backend:latest